const mockModule = {
  setupPlayer: jest.fn().mockResolvedValue(undefined),
  updateOptions: jest.fn().mockResolvedValue(undefined),

  load: jest.fn().mockResolvedValue(0),
  reset: jest.fn().mockResolvedValue(undefined),
  play: jest.fn().mockResolvedValue(undefined),
  pause: jest.fn().mockResolvedValue(undefined),
  stop: jest.fn().mockResolvedValue(undefined),
  setPlayWhenReady: jest.fn().mockResolvedValue(true),
  getPlayWhenReady: jest.fn().mockResolvedValue(false),
  seekTo: jest.fn().mockResolvedValue(undefined),
  seekBy: jest.fn().mockResolvedValue(undefined),
  setVolume: jest.fn().mockResolvedValue(undefined),
  getVolume: jest.fn().mockResolvedValue(1),
  setRate: jest.fn().mockResolvedValue(undefined),
  getRate: jest.fn().mockResolvedValue(1),
  getProgress: jest.fn().mockResolvedValue({ position: 0, duration: 0, buffered: 0 }),
  getPlaybackState: jest.fn().mockResolvedValue({ state: 'none' }),
  retry: jest.fn().mockResolvedValue(undefined),

  add: jest.fn().mockResolvedValue(undefined),
  move: jest.fn().mockResolvedValue(undefined),
  remove: jest.fn().mockResolvedValue(undefined),
  removeUpcomingTracks: jest.fn().mockResolvedValue(undefined),
  skip: jest.fn().mockResolvedValue(undefined),
  skipToNext: jest.fn().mockResolvedValue(undefined),
  skipToPrevious: jest.fn().mockResolvedValue(undefined),
  updateMetadataForTrack: jest.fn().mockResolvedValue(undefined),
  updateNowPlayingMetadata: jest.fn().mockResolvedValue(undefined),
  setQueue: jest.fn().mockResolvedValue(undefined),
  getQueue: jest.fn().mockResolvedValue([]),
  setRepeatMode: jest.fn().mockResolvedValue(0),
  getRepeatMode: jest.fn().mockResolvedValue(0),
  getTrack: jest.fn().mockResolvedValue(undefined),
  getActiveTrackIndex: jest.fn().mockResolvedValue(undefined),
  getActiveTrack: jest.fn().mockResolvedValue(undefined),

  addListener: jest.fn(),
  removeListeners: jest.fn(),

  getConstants: jest.fn().mockReturnValue({
    CAPABILITY_PLAY: 0,
    CAPABILITY_PLAY_FROM_ID: 1,
    CAPABILITY_PLAY_FROM_SEARCH: 2,
    CAPABILITY_PAUSE: 3,
    CAPABILITY_STOP: 4,
    CAPABILITY_SEEK_TO: 5,
    CAPABILITY_SKIP: 6,
    CAPABILITY_SKIP_TO_NEXT: 7,
    CAPABILITY_SKIP_TO_PREVIOUS: 8,
    CAPABILITY_SET_RATING: 9,
    CAPABILITY_JUMP_FORWARD: 10,
    CAPABILITY_JUMP_BACKWARD: 11,
    STATE_NONE: 'none',
    STATE_READY: 'ready',
    STATE_PLAYING: 'playing',
    STATE_PAUSED: 'paused',
    STATE_STOPPED: 'stopped',
    STATE_BUFFERING: 'buffering',
    STATE_LOADING: 'loading',
    RATING_HEART: 0,
    RATING_THUMBS_UP_DOWN: 1,
    RATING_3_STARS: 2,
    RATING_4_STARS: 3,
    RATING_5_STARS: 4,
    RATING_PERCENTAGE: 5,
    REPEAT_OFF: 0,
    REPEAT_TRACK: 1,
    REPEAT_QUEUE: 2,
    PITCH_ALGORITHM_LINEAR: 0,
    PITCH_ALGORITHM_MUSIC: 1,
    PITCH_ALGORITHM_VOICE: 2,
  }),

  acquireWakeLock: jest.fn().mockResolvedValue(undefined),
  abandonWakeLock: jest.fn().mockResolvedValue(undefined),
  validateOnStartCommandIntent: jest.fn().mockResolvedValue(true),
};

export const Constants = mockModule.getConstants();
export default mockModule;
